resource_group_name    = "appservice-rg"
location              = "centralus"
sql_server_name       = "appsqlserver123"
sql_db_name           = "appdb"
admin_username        = "sqladmin"
admin_password        = "P@ssw0rd123!"
app_service_name      = "myapp-service1"
app_service_plan_name = "myapp-plan"